import type { Citation } from '../domain/models.ts';

export const citations = [
  { id: 'noaa-light', short: 'NOAA · luz', title: 'How far does light travel in the ocean?', publisher: 'NOAA National Ocean Service', year: 's. f.', url: 'https://oceanservice.noaa.gov/facts/light_travel.html', scope: 'Tres zonas de luz; profundidades oceánicas de referencia.' },
  { id: 'cmecs', short: 'NOAA · transparencia', title: 'CMECS Application for Photic Quality — Euphotic Depth', publisher: 'NOAA NCEI', year: '2012', url: 'https://www.ncei.noaa.gov/waf/data-atlas-waf/products/html/environmentalPlates/CMECS_PhoticQualityLayerGuidance.htm', scope: 'Definición eufótica, radiación, transparencia y turbidez. Sus mapas son del golfo de México; no se extrapolan a Colombia.' },
  { id: 'siac', short: 'SIAC · regiones', title: 'Regional', publisher: 'Sistema de Información Ambiental de Colombia', year: 's. f.', url: 'https://www.siac.gov.co/regional', scope: 'Contexto regional del Caribe, Pacífico, Orinoquía y Amazonía.' },
  { id: 'ideam', short: 'IDEAM · cuencas', title: 'Boletín de Alertas Hidrológicas: áreas hidrográficas de Colombia', publisher: 'IDEAM', year: 's. f.', url: 'https://ideam.gov.co/sala-de-prensa/boletines/Bolet%C3%ADn-de-Alertas-Hidrol%C3%B3gicas-%28BAH%29', scope: 'Cinco áreas hidrográficas; referencia de los nombres, no de límites cartográficos.' },
  { id: 'pnn-plan', short: 'PNN · plan de manejo', title: 'Plan de manejo PNN Los Corales del Rosario y de San Bernardo 2019–2024', publisher: 'Parques Nacionales Naturales de Colombia', year: '2020', url: 'https://www.parquesnacionales.gov.co/wp-content/uploads/2020/10/planes-de-manejo-pnn-los-corales-del-rosario-y-san-bernardo.pdf', scope: 'Arrecifes y pastos (pp. 116–129), especies (p. 77), presiones (pp. 143–150). Documento histórico; no se presentan categorías de amenaza como actuales.' },
  { id: 'pnn-restoration', short: 'PNN · restauración', title: 'Conozca la alianza comunitaria por el cuidado de los arrecifes de coral en Corales del Rosario y San Bernardo', publisher: 'Parques Nacionales Naturales de Colombia', year: '2026', url: 'https://www.parquesnacionales.gov.co/sala-prensa/conozca-la-alianza-comunitaria-por-el-cuidado-de-los-arrecifes-de-coral-en-el-parque-nacional-natural-corales-del-rosario-y-san-bernardo/', scope: 'Guarderías de coral y participación comunitaria; publicación del 27 de enero.' },
  { id: 'wetlands', short: 'Biota · humedales', title: 'Identificación espacial de los sistemas de humedales continentales de Colombia', publisher: 'Flórez et al. · Biota Colombiana', year: '2016', url: 'https://doi.org/10.21068/C2016s01a03', mirror: 'https://revistas.humboldt.org.co/index.php/biota/article/view/409', scope: 'Humedales continentales y regulación hídrica. No se reproducen sus mapas.' },
  { id: 'ayapel', short: 'Biota · Ayapel', title: 'Variación temporal de la morfología funcional del fitoplancton en una planicie inundable del Caribe colombiano', publisher: 'Zabala Agudelo et al. · Biota Colombiana', year: '2019', url: 'https://doi.org/10.21068/c2019.v20n02a01', mirror: 'https://revistas.humboldt.org.co/index.php/biota/article/view/582', scope: 'Fitoplancton de Ayapel, inundación, sequía y presiones ambientales; no es evidencia de todos los cuerpos de agua.' },
  { id: 'caribbean-plankton', short: 'Biota · fitoplancton', title: 'Fitoplancton de la provincia oceánica del mar Caribe colombiano. Diez años de historia', publisher: 'Rodríguez-Moreno et al. · Biota Colombiana', year: '2022', url: 'https://revistas.humboldt.org.co/index.php/biota/article/view/903', mirror: 'https://revistas.humboldt.org.co/index.php/biota/article/download/903/1054', scope: 'Diversidad y registros del fitoplancton oceánico colombiano; lectura alternativa disponible.' },
  { id: 'food-web', short: 'NOAA · red trófica', title: 'Aquatic food webs', publisher: 'NOAA Education', year: 's. f.', url: 'https://www.noaa.gov/education/resource-collections/marine-life/aquatic-food-webs', scope: 'Productores, consumidores, flujo de energía y reciclaje de nutrientes.' },
  { id: 'decomposers', short: 'NOAA · descomposición', title: 'Determine components of the food web in an estuary', publisher: 'NOAA Institutional Repository', year: 's. f.', url: 'https://repository.library.noaa.gov/view/noaa/35467/noaa_35467_DS1.pdf', scope: 'Bacterias y hongos como descomponedores; red estuarina educativa.' },
  { id: 'grazing', short: 'NOAA · herbivoría', title: 'Restoring Natural Grazing Processes Can Help Coral Reefs', publisher: 'NOAA Fisheries', year: '2019', url: 'https://www.fisheries.noaa.gov/feature-story/restoring-natural-grazing-processes-can-help-coral-reefs', scope: 'Peces herbívoros, control de algas y conservación de arrecifes.' },
  { id: 'plants', short: 'NOAA · pastos', title: 'Why are aquatic plants so important?', publisher: 'NOAA National Ocean Service', year: 's. f.', url: 'https://oceanservice.noaa.gov/facts/underwaterplants.html', scope: 'Vegetación sumergida, refugio, alimento y estabilización de sedimentos.' },
  { id: 'nutrients', short: 'EPA · nutrientes', title: 'The Effects: Environment', publisher: 'US Environmental Protection Agency', year: 's. f.', url: 'https://www.epa.gov/nutrientpollution/effects-environment', scope: 'Exceso de nutrientes, algas, reducción de luz e hipoxia.' },
  { id: 'bleaching', short: 'NOAA · blanqueamiento', title: 'What is coral bleaching?', publisher: 'NOAA National Ocean Service', year: 's. f.', url: 'https://oceanservice.noaa.gov/facts/coral_bleach.html', scope: 'Estrés térmico, pérdida de algas simbióticas y posibilidad de recuperación.' },
  { id: 'wetland-services', short: 'EPA · servicios', title: 'Wetlands', publisher: 'US Environmental Protection Agency', year: 's. f.', url: 'https://www.epa.gov/report-environment/wetlands', scope: 'Hábitat, inundación, erosión y calidad del agua.' },
] as const satisfies readonly Citation[];
